version: "3.5"

services:
  cardano-db-sync-api:
    image: wutzebaer/cardano-db-sync-api:latest
    ports:
      - 127.0.0.1:8094:8080
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
      - spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
      - spring.datasource.url=${SPRING_DATASOURCE_URL}
networks: 
  default: 
    external: 
      name: cardano-tools-network